/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testcrud;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arumia
 */
public class frmMain extends javax.swing.JFrame {
    
    public frmMain() {
        initComponents();
        setJam();
        setTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNIS = new javax.swing.JTextField();
        jtNama = new javax.swing.JTextField();
        jtKelas = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtTempatLahir = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelJam = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonPrint = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        buttonEdit1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_siswa = new javax.swing.JTable();

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 20, 90, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 60, 90, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 180, 90, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kelas");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 260, 90, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 300, 90, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 340, 90, 30);

        jtNIS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNISActionPerformed(evt);
            }
        });
        jPanel1.add(jtNIS);
        jtNIS.setBounds(120, 20, 230, 30);

        jtNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(jtNama);
        jtNama.setBounds(120, 60, 230, 30);

        jtKelas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtKelasActionPerformed(evt);
            }
        });
        jPanel1.add(jtKelas);
        jtKelas.setBounds(120, 260, 230, 30);

        jtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jtEmail);
        jtEmail.setBounds(120, 300, 230, 30);

        buttonGroup1.add(rbLaki);
        rbLaki.setForeground(new java.awt.Color(255, 255, 255));
        rbLaki.setText("Laki - Laki");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });
        jPanel1.add(rbLaki);
        rbLaki.setBounds(130, 190, 90, 23);

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        rbPerempuan.setText("Perempuan");
        jPanel1.add(rbPerempuan);
        rbPerempuan.setBounds(130, 220, 90, 23);

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane1.setViewportView(taAlamat);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 350, 230, 96);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal Lahir");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 140, 100, 30);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tempat Lahir");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 100, 100, 30);

        jtTempatLahir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtTempatLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTempatLahirActionPerformed(evt);
            }
        });
        jPanel1.add(jtTempatLahir);
        jtTempatLahir.setBounds(120, 100, 230, 30);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(120, 140, 230, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 150, 370, 460);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM MALANG");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 20, 1360, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("The Real Informatic School");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 50, 1360, 30);

        labelJam.setForeground(new java.awt.Color(255, 255, 102));
        labelJam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJam.setText("Jam :");
        jPanel2.add(labelJam);
        labelJam.setBounds(670, 90, 510, 30);

        labelTanggal.setForeground(new java.awt.Color(255, 255, 102));
        labelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTanggal.setText("Tanggal :");
        jPanel2.add(labelTanggal);
        labelTanggal.setBounds(0, 90, 670, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1360, 140);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setLayout(null);

        buttonPrint.setText("Print");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });
        jPanel3.add(buttonPrint);
        buttonPrint.setBounds(670, 20, 80, 30);

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSave);
        buttonSave.setBounds(120, 20, 80, 30);

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(buttonDelete);
        buttonDelete.setBounds(230, 20, 80, 30);

        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel3.add(buttonClear);
        buttonClear.setBounds(340, 20, 80, 30);

        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(buttonRefresh);
        buttonRefresh.setBounds(450, 20, 80, 30);

        buttonEdit1.setText("Edit");
        buttonEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEdit1ActionPerformed(evt);
            }
        });
        jPanel3.add(buttonEdit1);
        buttonEdit1.setBounds(560, 20, 80, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(390, 150, 960, 70);

        jPanel4.setLayout(null);

        t_siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "TempatLahir", "TanggalLahir", "JK", "Kelas", "Email", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_siswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(t_siswa);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 960, 380);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(390, 230, 960, 310);

        setBounds(0, 0, 1376, 659);
    }// </editor-fold>//GEN-END:initComponents

    private void jtKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtKelasActionPerformed

    private void jtNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNISActionPerformed

    private void jtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNamaActionPerformed

    private void jtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
        String tanggal = dateFormat.format(jDateChooser1.getDate());

        String JK = "";
        if(rbLaki.isSelected())
                {
                    JK = "L";
                }
                else
                {
                    JK = "P";
                }
        
        
        if(jtNIS.getText().equals("") || jtNama.getText().equals("")
                || jtTempatLahir.getText().equals("") || tanggal.equals("")
                || JK.equals("") || jtKelas.getText().equals("") 
                || jtEmail.getText().equals("") || taAlamat.getText().equals("")    
                        
                )
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data Anda","Error",JOptionPane.WARNING_MESSAGE);
        }
        else
        {               
           
            String SQL = "INSERT INTO t_siswa (NIS,Nama,TempatLahir,TanggalLahir,JK,Kelas,Email,Alamat)"
                    + "VALUES('"+jtNIS.getText()+"','"+jtNama.getText()+"','"+jtTempatLahir.getText()+"','"
                    +tanggal+"','"+JK+"','"+jtKelas.getText()+"','"+jtEmail.getText()+"','"+taAlamat.getText()+"')";
            
            int status = KoneksiDB.execute(SQL);
            
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        int baris = t_siswa.getSelectedRow();
        if(baris != -1)
        {
            String NIS = t_siswa.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        jtNIS.setText("");
        jtNama.setText("");
        jtTempatLahir.setText("");
        buttonGroup1.clearSelection();
        jtEmail.setText("");
        taAlamat.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        selectData();
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
      MessageFormat header = new MessageFormat("Biodata SIswa SMK Telkom Malang");
      MessageFormat footer = new MessageFormat("Page {0,number,integer}      ");
      
      try{
          t_siswa.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
          }
      catch(java.awt.print.PrinterException e)
      {
          System.err.format("Cannot print %s%n", e.getMessage());
      }      
    }//GEN-LAST:event_buttonPrintActionPerformed

    private void buttonEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEdit1ActionPerformed

    private void jtTempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTempatLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTempatLahirActionPerformed

    private void t_siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_siswaMouseClicked
        int baris = t_siswa.getSelectedRow();
        if(baris != -1)
        {
            jtNIS.setText(t_siswa.getValueAt(baris, 0).toString());
            jtNama.setText(t_siswa.getValueAt(baris, 1).toString());
            jtTempatLahir.setText(t_siswa.getValueAt(baris, 2).toString());

            SimpleDateFormat date = new SimpleDateFormat("yyy-MM-dd");
            Date dateFormat = null;
            try
            {
                dateFormat = date.parse(t_siswa.getValueAt(baris, 3).toString());
            }
            catch(ParseException ex)
            {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null,ex);
            }
            
            jDateChooser1.setDate(dateFormat);
           
            if("Laki - Laki".equals(t_siswa.getValueAt(baris, 4).toString()))
            {
                rbLaki.setSelected(true);
            }
            else
            {
                rbPerempuan.setSelected(true);
            }
            
            jtKelas.setText(t_siswa.getValueAt(baris, 5).toString());
            jtEmail.setText(t_siswa.getValueAt(baris, 6).toString());
            taAlamat.setText(t_siswa.getValueAt(baris, 7).toString());

        }
    }//GEN-LAST:event_t_siswaMouseClicked

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonPrint;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonSave;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtKelas;
    private javax.swing.JTextField jtNIS;
    private javax.swing.JTextField jtNama;
    private javax.swing.JTextField jtTempatLahir;
    private javax.swing.JLabel labelJam;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable t_siswa;
    private javax.swing.JTextArea taAlamat;
    // End of variables declaration//GEN-END:variables

    private void selectData(){
        String kolom[] = {"NIS","Nama","TempatLahir","TanggalLahir","JK","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try{
            while(rs.next())
            {
               String NIS = rs.getString(1);
               String Nama = rs.getString(2);
               String TempatLahir = rs.getString(3);
               String TanggalLahir = rs.getString(4);
               
               String JK = "";
               
               if("L".equals(rs.getString(5)))
               {
                   JK = "Laki - Laki";
               }
               else
               {
                   JK = "Perempuan";
               }
               
               String Kelas = rs.getString(6);
               String Email = rs.getString(7);
               String Alamat = rs.getString(8);
               String data[] = {NIS,Nama,TempatLahir,TanggalLahir,JK,Kelas,Email,Alamat};
               dtm.addRow(data);
            }
        }
        catch(SQLException ex)
        {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        t_siswa.setModel(dtm);
    }
    
    public void setTanggal()
    {
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM//yyy");
        labelTanggal.setText(kal.format(skrg));
    } 
    
    public void setJam()
    {
        ActionListener taskPerformer = new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                
                String jam = Integer.toString(nilai_jam);
                String menit = Integer.toString(nilai_menit);
                String detik = Integer.toString(nilai_detik);
                labelJam.setText("Jam " + jam + ":" + menit + ":" + detik);
            }
        };
         new Timer(100, taskPerformer).start();       
    }
    
}
